"""add description and end_date to position

Revision ID: 4d495f7356dc
Revises: 80bafd46c643
Create Date: 2025-12-02 16:11:54.409522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d495f7356dc'
down_revision = '80bafd46c643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('position', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'end_date')
    op.drop_column('position', 'description')
    # ### end Alembic commands ###
