"""Add student_id to student model

Revision ID: 797fb964507a
Revises: 4d495f7356dc
Create Date: 2025-12-02 17:13:42.378367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797fb964507a'
down_revision = '4d495f7356dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('student_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'student', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 'student_id')
    # ### end Alembic commands ###
