"""added state column and its appendages

Revision ID: 80bafd46c643
Revises: 
Create Date: 2025-11-27 14:38:04.662143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80bafd46c643'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortlist', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortlist', 'state')
    # ### end Alembic commands ###
